edit_model_name: "gpt-j-6b"
layers: [25,26,27]
num_steps: 25
batch_size: 1
max_length: 30
lr: 5.e-4
weight_decay: 0
kl_factor: 0
norm_constraint: false
rewrite_module_tmp: "transformer.h.{}.mlp.fc_out.weight"
layer_module_tmp: "transformer.h.{}"
mlp_module_tmp: "transformer.h.{}.mlp"
attn_module_tmp: "transformer.h.{}.attn"
ln_f_module: "transformer.ln_f"
lm_head_module: "lm_head"

