edit_model_name: "llama-7b"
layers: [28,29,31]
num_steps: 25
batch_size: 1
max_length: 30
lr: 4.e-5
weight_decay: 0
kl_factor: 0
norm_constraint: false
rewrite_module_tmp: "model.layers.{}.mlp.down_proj.weight"
layer_module_tmp: "model.layers.{}"
mlp_module_tmp: "model.layers.{}.mlp"
attn_module_tmp: "model.layers.{}.self_attn"
ln_f_module: "model.norm"
lm_head_module: "lm_head"

